# Generated by Django 4.1.4 on 2022-12-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('anons', models.CharField(max_length=250, verbose_name='Anons')),
                ('full_text', models.TextField(verbose_name='Review')),
                ('comment', models.CharField(max_length=250, verbose_name='Comment')),
                ('date', models.DateTimeField(verbose_name='Date of publication')),
            ],
            options={
                'verbose_name': 'Forum',
                'verbose_name_plural': 'Site Forum',
            },
        ),
    ]
