# Generated by Django 4.1.4 on 2022-12-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='comment',
        ),
    ]
