# Generated by Django 4.1.4 on 2022-12-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_forum_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='comment',
        ),
    ]
