# Generated by Django 4.1.4 on 2022-12-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_remove_forum_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='comment',
            field=models.TextField(default=False, verbose_name='Comment'),
        ),
    ]
