# Generated by Django 4.1.4 on 2022-12-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_forum_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
    ]
