# Generated by Django 4.1.4 on 2022-12-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_forum_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='date',
            field=models.DateField(verbose_name='Date of publication'),
        ),
    ]
