# Generated by Django 4.1.4 on 2022-12-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_comment_forumcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='forumcomment',
            name='forum',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='ForumComment',
        ),
    ]
